# Generated by Django 3.2.9 on 2021-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_paid',
            field=models.BooleanField(default=False),
        ),
    ]
