# Generated by Django 3.2.9 on 2021-11-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_order_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
