# Generated by Django 3.2.9 on 2021-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
