# Generated by Django 3.2.9 on 2021-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_table_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
